### ISSUE TITLE
[Question] Compatible with GA4?

### ISSUE THREAD

**Issue by watarutmnh** [nystudio107/craft3-instantanalytics#64]
Hi, is the plugin compatible with GA4?
Thanks,

**Comment by khalwat** [comment]
It is not.

**Comment by watarutmnh** [comment]
Okay thanks.

**Comment by karensg** [comment]
Are there any plans to support it in the future?
Old GA will sunset on July 1, 2023.

**Comment by khalwat** [comment]
The underlying library doesn't support GA4 AFAIK. https://github.com/theiconic/php-ga-measurement-protocol/issues/94

**Comment by Floriswijgergangs** [comment]
Maybe this library is a solution to upgrade for GA4?
https://github.com/br33f/php-GA4-Measurement-Protocol

**Comment by khalwat** [comment]
Oh nice @Floriswijgergangs !

**Comment by smockensturm** [comment]
So the GA4 compatibility question is still open, yes? Can we plan on this?

**Comment by khalwat** [comment]
It's an open question, but I've begun work on seeing how feasible it will be.

It's possible that API changes would be required, but I'm unsure currently.

**Comment by Romanavr** [comment]
@khalwat 
Could you give an update please?
Because on some projects we use the plugin, but due to the fact that the library under the hood is not compatible with GA4, we can't move to GA4.

Anyway, thanks for your hard work!

**Comment by khalwat** [comment]
So I have a working implementation of this; I just need to do some QA on it, and update the docs. Since they are sunsetting the old API, there's no great reason to keep it around.

**Comment by localcraig** [comment]
@khalwat 

Hey! Any update/timeline on this? 

Thanks!

**Comment by MaddieB-MWCompany** [comment]
@khalwat 

Hey! Do you think this update will be released soon? 

Thank you!

**Comment by chrismou** [comment]
@khalwat Is there anything we can do to help this along? Like a public branch we could test?

I have clients chasing me to get this updated and am trying to decide whether its worth holding off and waiting for this plugin update, or just bite the bullet and start moving them over to using JS. Appreciate you may be busy, just need to know what the plan is as the sunset deadline is getting closer

**Comment by khalwat** [comment]
It's in active development, I'm hoping to have a beta release that you can check out in 2 weeks

**Comment by smockensturm** [comment]
Hey @khalwat we need to know what's up so we can make a plan.

**Comment by gaelpleeroy** [comment]
I'm also very interested by GA4 support.

**Comment by khalwat** [comment]
We have the plugin pretty close to being ready to beta test.

We decided to deprecate the old "Instant Analytics" plugin, and name the new plugin "Instant Analytics GA4", primarily because the API was completely rewritten.

This was by necessity because GA4 has been completely rewritten in a way that is far deeper than just the API (also conceptually). And Instant Analytics needs to reflect these API changes.

We're at the stage now where we are working on getting the documentation done, I'd estimate we should have a beta version published in the Craft Plugin Store in a week or so.

**Comment by uandco** [comment]
Hi @khalwat , any update on the release date of that beta plugin?

**Comment by khalwat** [comment]
I've pushed to the public repo:

https://github.com/nystudio107/craft-instantanalytics-ga4

and have just a bit of cleanup on the docs and such before I'll release it to the plugin store as a beta. I'm shooting for tomorrow

**Comment by khalwat** [comment]
Released 4.0.0-beta.1: https://github.com/nystudio107/craft-instantanalytics-ga4

Also submitted it to the plugin store:

<img width="628" alt="Screenshot 2023-06-13 at 14 25 41" src="https://github.com/nystudio107/craft-instantanalytics/assets/7570798/a7544388-88d8-450e-bc85-2b2eb3110cd6">

Docs: https://nystudio107.com/docs/instant-analytics-ga4/

Any issues or discussion can be moved over there: https://github.com/nystudio107/craft-instantanalytics-ga4/issues

**Comment by Romanavr** [comment]
If somebody looking for documentation -> https://github.com/nystudio107/craft-instantanalytics-ga4/blob/develop-v4/docs/docs/using.md

**Comment by khalwat** [comment]
Forgot to update the docs URL in the original post. They are here:

https://nystudio107.com/docs/instant-analytics-ga4/

**Comment by smockensturm** [comment]
Hi @khalwat 

Do licenses transfer?

On a scale of 1-10, what is your sense of obligation for making the new plugin Craft 3 / Commerce 3 compatible until end-of-life? (April 30, 2024)

Because this puts us in a little pickle as we were not quite prepared, nor have the budget, to do those major upgrades right this second.

Or perhaps you can give us a sense of what that would take and we can either a) fork it or b) pay you handsomely. What? Half a days work? More?

Thanks for everything.

**Comment by khalwat** [comment]
@smockensturm please create a new issue for this, and I will answer you there

**Comment by smockensturm** [comment]
Sure @khalwat 

Here or in the new plugin repo? :)

**Comment by khalwat** [comment]
On the GA4 plugin repo: https://github.com/nystudio107/craft-instantanalytics-ga4/issues
